### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by stevenmusumeche** [malijs/mali#43]
This project is wonderful after working with grpc-node. Are there plans to support TypeScript in this library, or add definition files?

**Comment by bojand** [comment]
TypeScript is not something I use much, but I agree it would be useful to provide a typings / definition file. I will try and add one. Not really an expert, so help would be appreciated.

**Comment by stevenmusumeche** [comment]
I'd be happy to help.  It looks like you already have good JSDoc annotations, and typescript typings can be generated directly from them.

**Comment by danwbyrne** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28548

it isn't perfect at all, so any help would be great. Its fairly template-y but enough so that it is usable. There is a lot of `any` types because `object` typing wasn't playing well with some of the arg assertions.

**Comment by bojand** [comment]
Hello, Thanks for this! I'm without computer and with limited access for a week but will try and take a deeper look into this after. Quickly looking there should be some room for improvements: for example port should always be a number; the type is an enum as defined in package [mali-call-types] (https://github.com/malijs/mali-call-types) and the core request and response objects (within Mali request and response respectively) should be defined somewhere in grpc as `RequestType` and `RespknseType` I believe since they use typescript themselves in the JavaScript library.

**Comment by danwbyrne** [comment]
Hey @bojand , I'm not sure which `port` property you a referring to because doing `app.start('123.123.123.123')` should work on a string no?

also the issue with GRPC types (I saw they were the returns as well) is that they aren't hosted on DT, they are exported by GRPC themselves which is an issue for adding them to a DT repo.

Feel free to submit a PR at DT and I'll still be watching it to approve them. For now though this is about the maximum time I can spend on it.

**Comment by bojand** [comment]
@stevenmusumeche @danwbyrne Can you please take a look #53. I would appreciate review and feedback. Thank you.

**Comment by sykorax** [comment]
Hey there,

I'm having problems with generics. In general the incoming context is a fixed type. Because of that TypeScript doesn't really like the following:

![image](https://user-images.githubusercontent.com/5334912/54355255-dcfac880-4658-11e9-89a5-bf6eff560c8f.png)

Is it possible to transform the Request type to be generic?
Maybe something like:

```typescript
interface Context<RE, RP, MT> {
    name: string;
    fullName: string;
    service: string;
    package: string;
    app: Mali;
    call: any;
    request: Request<RE>;
    response: Response<RP>;
    req: GrpcRequest;
    res: GrpcResponse;
    type: string;
    metadata: MT | any;
    get(field: string): any;
    set(field: any, val?: any): void;
    sendMetadata(md: any): void;
    getStatus(field: string): any;
    setStatus(field: any, val?: any): void;
}
```

Where..
- RE = Request Type
- RP = Response Type
- MT = Metadata Type
